### ISSUE TITLE
Runtime error: Unknown node type: TestExpression

### ISSUE THREAD

**Issue by PeLaNo2** [maiqingqiang/ChatMLX#13]
Hi, after updating the 1.1.0 version of ChatMLX, the app is now not crashing, but I ran into this problem with a model that was downloaded through the MLX community in the settings of the app. I've tried multiple versions, and none seems to work.

![CleanShot 2567-10-04 at 09 48 31@2x](https://github.com/user-attachments/assets/3a4b8c42-05f6-43e0-a04c-fc5dd985dc34)

**Comment by maiqingqiang** [comment]
This is a compatibility issue with Llama3.2 in Jinja. The new version of Jinja has resolved this problem. I will update to the new version later.

https://github.com/maiqingqiang/Jinja/pull/4

https://github.com/maiqingqiang/ChatMLX/pull/12

**Comment by PeLaNo2** [comment]
I see, thank you for the quick solve!
