### ISSUE TITLE
Runtime error: The data couldn’t be read because it isn’t in the correct format.

### ISSUE THREAD

**Issue by yczhangsjtu** [maiqingqiang/ChatMLX#17]
On Mac Sonoma. Just installed the software from the latest release (1.1.2 (4)), and downloaded LLama3.2 (meta-llama/Llama-3.2-1B). Then see this error.
<img width="894" alt="image" src="https://github.com/user-attachments/assets/33af03ce-0f74-4d55-b2dc-181a63974076">

**Comment by maiqingqiang** [comment]
Please use the models provided by mlx-community.

https://huggingface.co/collections/mlx-community/llama32-66f6f2d29884fa00e92d2411

**Comment by yczhangsjtu** [comment]
Thanks. Switched to mlx community version, then encountered another error.

#18
