### ISSUE TITLE
Cannot open with Xcode version 15.4

### ISSUE THREAD

**Issue by longbow007** [maiqingqiang/ChatMLX#2]
The alert says:
cannot be opened because it is in a future Xcode project file format. Adjust the project format using a compatible version of Xcode to allow it to be opened by this version of Xcode.

**Comment by maiqingqiang** [comment]
Oh, sorry. I developed it using Xcode 16.0.0 Beta 6, and I'll handle it later. If you're interested, feel free to submit a PR to fix it.

**Comment by maiqingqiang** [comment]
Xcode 16 Buildable Folders Break Xcode 15 Backwards Compatibility

https://blog.supereasyapps.com/xcode-16-buildable-folders-break-xcode-15-backwards-compatibility/
https://www.youtube.com/watch?v=n-W0CfHFyBg

**Comment by maiqingqiang** [comment]
Done
