### ISSUE TITLE
Model file storage path

### ISSUE THREAD

**Issue by lipengyu** [maiqingqiang/ChatMLX#25]
What is the default model data storage path? Whether the model custom storage path can be configured.

**Comment by johnmai-dev** [comment]
default path: `/Users/<user>/Library/Containers/johnmai.ChatMLX/Data/Documents/huggingface/models`
<img width="620" alt="image" src="https://github.com/user-attachments/assets/d6f5358a-5ef5-49fe-b0b9-201cae0ec589">

Custom storage path is under development.

**Comment by johnmai-dev** [comment]
duplicate #6
