### ISSUE TITLE
Phi-3.5-MoE support

### ISSUE THREAD

**Issue by okaneyo** [maiqingqiang/ChatMLX#3]
Add support for this incredible model

**Comment by maiqingqiang** [comment]
ChatMLX mainly relies on the support provided by [MLX Swift Examples](https://github.com/ml-explore/mlx-swift-examples).

Add Phi 3.5 MoE https://github.com/ml-explore/mlx-swift-examples/pull/116

I will update promptly after this PR is merged.

**Comment by DePasqualeOrg** [comment]
@okaneyo, you can test my attempt to implement Phi 3.5 MoE in https://github.com/ml-explore/mlx-swift-examples/pull/116 and tell me if it works. My MacBook unfortunately doesn't have enough RAM for me to test it myself.

**Comment by maiqingqiang** [comment]
> @okaneyo, you can test my attempt to implement Phi 3.5 MoE in [ml-explore/mlx-swift-examples#116](https://github.com/ml-explore/mlx-swift-examples/pull/116) and tell me if it works. My MacBook unfortunately doesn't have enough RAM for me to test it myself.

Thank you! @DePasqualeOrg
