### ISSUE TITLE
High cpu usage

### ISSUE THREAD

**Issue by 0zguner** [maiqingqiang/ChatMLX#8]
Hi,

Great work on this application. But cpu usage is really high and typing is laggy because of this as well. While answer is generated on the UI, cpu usage increases more than 100%

<img width="450" alt="Screenshot 2024-09-29 at 18 33 40" src="https://github.com/user-attachments/assets/24cbf7cf-13b3-41b7-988c-0c7aca7676de">
<img width="548" alt="Screenshot 2024-09-29 at 15 09 11" src="https://github.com/user-attachments/assets/50b0603d-d6d8-4c31-a006-9023d9c282ce">

**Comment by maiqingqiang** [comment]
https://github.com/maiqingqiang/ChatMLX/issues/9#issuecomment-2381993999
