### ISSUE TITLE
[Feature request] Option to disable blur/transparent background

### ISSUE THREAD

**Issue by 0zguner** [maiqingqiang/ChatMLX#9]
Hi

Since the application is mostly showing text,
I think it would be nice to have option to disable transparent background.

A dark mode option would also be very useful.

Regards

**Comment by maiqingqiang** [comment]
Thank you very much for your suggestion. Of course, you can also adjust the window appearance in the settings.

![image](https://github.com/user-attachments/assets/ab20ffda-2210-450a-b16c-1698d21adfc5)
